### ISSUE TITLE
Embedding $$ inside \text makes error

### ISSUE THREAD

**Issue by tim-watcha** [4g3nt81lly/TeX-ScratchPaper#2]
This is not working.
`abc \text{ abc $abc$ }`

but this is working
`abc \text{ abc \(abc\) }`

I guess this is related to [this](https://github.com/KaTeX/KaTeX/issues/5) issue.

anyway thank you for your effort to make this. I was looking for the tex app based on KaTeX because of notion-things haha

**Comment by tim-watcha** [comment]
(in Display Mode)

**Comment by 4g3nt81lly** [comment]
Wow! Thank you so much for your comment!
I'll look into that and see if there's a workaround if it really was an issue with KaTeX. :)

**Comment by tim-watcha** [comment]
I did in on Display Mode + f(x)
<img width="935" alt="스크린샷 2022-08-03 오후 12 34 21" src="https://user-images.githubusercontent.com/92134765/182518497-6f6dec3c-13f2-4d51-81fa-415b199198d7.png">
<img width="607" alt="스크린샷 2022-08-03 오후 12 34 02" src="https://user-images.githubusercontent.com/92134765/182518504-18d7e837-088b-4373-86a8-76f4950c3df6.png">

**Comment by 4g3nt81lly** [comment]
@tim-watcha The issue is fixed in the [new build](https://github.com/4g3nt81lly/TeX-ScratchPaper/releases/tag/v0.1.0-alpha(2))! YAY
Feel free to try it out!

**Comment by tim-watcha** [comment]
d9990222a7631e4b98b24b8eb19911957348c6ec resolved this issue! Thank you
